name: "🗺️ Roadmap"
description: Planned projects in the future to do. (⚠️ For contributors only)
title: "🗺️ Roadmap: <title>"
labels: [
  "Type ◦ Roadmap"
]
body:
  - type: markdown
    attributes:
      value: |
        1. This issue type is different from feature requests.
        2. This issue type is typically used by the developers of this repository to create and track new features
           that have been planned in a future version of TVApp2.
        3. Only use this issue type if you have been instructed to do so by a repository contributor.
        4. Describe the benefits of this plan, and what needs to be taken into consideration during implementation.
        5. Be detailed but to the point.

        <br />

  - type: input
    id: roadmap-version-target
    attributes:
      label: Target Version
      description: |
        Which version are we aiming to introduce this into TVApp2?
      placeholder: "v1.0.0"
    validations:
      required: true
